### ISSUE TITLE
Unable to Use Pymmcore in Windows 10 64 bit, Anaconda 32 bit

### ISSUE THREAD

**Issue by harshmathur1990** [micro-manager/pymmcore#57]
Hi,

I am trying to use Andor iKon L and Apogee Alta F6 camera with pymmcore.

Steps to reproduce the bug: 
1. Windows 10 Pro 64 bit Platform
2. Download 32 bit anaconda.
3. Make an virtual environment with python 3.7.11 (Win 32 bit)
4. conda activate virtual-environment (created in step 3)
4. install pymmcore using pip (python -m pip)
5. install Micromanager 2.0 (32 bit).
6. make configuration files for Andor and Apogee camera using Micromanager hardware wizard. Both the cameras work with micromanager software.

Some Outputs:
```
(Python3-32-1) C:\Program Files (x86)\Micro-Manager-2.0>python
Python 3.7.11 (default, Jul 27 2021, 09:46:33) [MSC v.1916 32 bit (Intel)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('32bit', 'WindowsPE')
>>> import pymmcore
>>> pymmcore.CMMCore().getAPIVersionInfo()
'Device API version 70, Module API version 10'
>>> mmc = pymmcore.CMMCore()
>>> mm_dir = 'C:\Program Files (x86)\Micro-Manager-2.0'
>>> mmc.setDeviceAdapterSearchPaths([mm_dir])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: Line 7: Device,Andor,Andor,Andor
Failed to load device "Andor" from adapter module "Andor" [ Failed to load device adapter "Andor" [ Failed to load module "C:\Program Files (x86)\Micro-Manager-2.0\mmgr_dal_Andor.dll" [ %1 is not a valid Win32 application. ] ] ]
>>>
```

AndorIKonL.cfg
```
# Generated by Configurator on Sun Feb 13 11:24:28 IST 2022

# Reset
Property,Core,Initialize,0

# Devices
Device,Andor,Andor,Andor

# Pre-init settings for devices
Property,Andor,Camera,| iKon | DZ936_BV~28 | 17872 |

# Pre-init settings for COM ports

# Hub (parent) references

# Initialize
Property,Core,Initialize,1

# Delays

# Focus directions

# Roles
Property,Core,Camera,Andor
Property,Core,AutoShutter,1

# Camera-synchronized devices

# Labels

# Configuration presets
# Group: Channel

# Group: System
# Preset: Startup
```

**Comment by marktsuchida** [comment]
It looks like you have already checked all the things I would have suspected immediately.

Except maybe one: can you see if it helps to change the current directory to `mm_dir` while loading the config? (See https://github.com/micro-manager/pymmcore#loading-device-adapters-on-windows.) Usually if this is the problem you get a different error, but it's worth checking.

If that doesn't help, can you try loading the demo configuration from pymmcore? It would help to first determine whether this is an Andor-specific issue or something to do with the 32-bit Micro-Manager in general (which probably hasn't been tested much).

Please also be aware that we no longer build Micro-Manager for 32-bit, so there will be no future updates.

**Comment by harshmathur1990** [comment]
Hi,

Thank you for looking into this.

I am forced to use 32 bit version because Apogee Alta F6 camera dlls do not support 64 bit and I want to use Andor iKonL and Apogee Alta simultaneously.

As you rightly pointed out about the current directory, if you see the output, the python is initiated from the micromanager directory itself. Hence the current directory is correct.

Thank you in advance for looking into this, I will be grateful if you suggest some solution for this.

Thank you.

Regards,
Harsh

**Comment by marktsuchida** [comment]
Oops, sorry I missed the current directory part.

Could you see what happens if you load the demo config (`MMConfig_demo.cfg`)?

**Comment by harshmathur1990** [comment]
Hi,

it gave the same error. Printing the outputs below.

I believe the issue is the 32 bit whl is somehow linked to 64-bit version.

```

(Python3-32-1) C:\Users\IIAP-IPC>cd ../../

(Python3-32-1) C:\>cd "Program Files (x86)"

(Python3-32-1) C:\Program Files (x86)>cd Micro-Manager-2.0

(Python3-32-1) C:\Program Files (x86)\Micro-Manager-2.0>python
Python 3.7.11 (default, Jul 27 2021, 09:46:33) [MSC v.1916 32 bit (Intel)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('32bit', 'WindowsPE')
>>> import pymmcore
>>> pymmcore
<module 'pymmcore' from 'C:\\Users\\IIAP-IPC\\anaconda3-32-bit\\envs\\Python3-32-1\\lib\\site-packages\\pymmcore\\__init__.py'>
>>> pymmcore.CMMCore().getAPIVersionInfo()
'Device API version 70, Module API version 10'
>>> mmc = pymmcore.CMMCore()
>>> import os
>>>  mm_dir = 'C:\Program Files (x86)\Micro-Manager-2.0'
  File "<stdin>", line 1
    mm_dir = 'C:\Program Files (x86)\Micro-Manager-2.0'
    ^
IndentationError: unexpected indent
>>> mm_dir = 'C:\Program Files (x86)\Micro-Manager-2.0'
>>> mmc.setDeviceAdapterSearchPaths([mm_dir])
>>> print (os.getcwd())
C:\Program Files (x86)\Micro-Manager-2.0
>>> mmc.loadSystemConfiguration(os.path.join(mm_dir, "MMConfig_demo.cfg"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: Line 7: Device,DHub,DemoCamera,DHub
Failed to load device "DHub" from adapter module "DemoCamera" [ Failed to load device adapter "DemoCamera" [ Failed to load module "C:\Program Files (x86)\Micro-Manager-2.0\mmgr_dal_DemoCamera.dll" [ %1 is not a valid Win32 application. ] ] ]


>>>
```

**Comment by marktsuchida** [comment]
I tried with Micro-Manager 2.0.0 (32-bit) and Python 3.7.9 (32-bit, python.org), installing via `python -m pip pymmcore`, but not using Conda. I did not get any errors loading `MMConfig_demo.cfg`. (It also worked with Python 3.9.10.)

I guess it could in theory be specific to Anaconda, but that would be a little surprising....

**Comment by harshmathur1990** [comment]
Hi,

I checked things

1. To check "mmgr_dal_DemoCamera.dll"
```
IIAP-IPC@DESKTOP-54LDTOM MINGW32 ~
$ '/c/Program Files (x86)/Micro-Manager-2.0/mmgr_dal_DemoCamera.dll'
bash: /c/Program Files (x86)/Micro-Manager-2.0/mmgr_dal_DemoCamera.dll: cannot execute binary file: Exec format error
```

2. ImageJ and Micromanager Version: 
```
ImageJ 1.51s; Java 1.8.0_152 [32-bit]; Windows 10 10.0; 18MB of 512MB (3%)
```
```
MM Studio version: 2.0.0
MMCore version 10.1.1
Device API version 70, Module API version 10
User: IIAP-IPC
Host: DESKTOP-54LDTOM
```

3. MS VC++ 2000 Redistributable:
```
Microsoft Visual C++ 2010 x86 Redistributable - 10.0.40219
```

I removed anaconda and micromanager and did a clean install with python 3.9.10 and I got the same error:

```
C:\Users\IIAP-IPC\AppData\Local\Programs\Python\Python39-32>python
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:01:48) [MSC v.1929 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymmcore
>>> mmc = pymmcore.CMMCore()
>>> import os
>>> mm_dir = 'C:\Program Files (x86)\Micro-Manager-2.0'
>>>
>>> mmc.setDeviceAdapterSearchPaths([mm_dir])
>>> os.chdir('C:\Program Files (x86)\Micro-Manager-2.0')
>>> print (os.getcwd())
C:\Program Files (x86)\Micro-Manager-2.0
>>> mmc.loadSystemConfiguration(os.path.join(mm_dir, "MMConfig_demo.cfg"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: Line 7: Device,DHub,DemoCamera,DHub
Failed to load device "DHub" from adapter module "DemoCamera" [ Failed to load device adapter "DemoCamera" [ Failed to load module "C:\Program Files (x86)\Micro-Manager-2.0\mmgr_dal_DemoCamera.dll" [ %1 is not a valid Win32 application. ] ] ]


>>>
```

**Comment by marktsuchida** [comment]
In
```
$ '/c/Program Files (x86)/Micro-Manager-2.0/mmgr_dal_DemoCamera.dll'
bash: /c/Program Files (x86)/Micro-Manager-2.0/mmgr_dal_DemoCamera.dll: cannot execute binary file: Exec format error
```
you need to include the word `file` before the path of the DLL ([`file`](https://en.wikipedia.org/wiki/File_(command)) is the name of the command that prints filetype information for a given file).

But it looks like all is correct, and I'm running out of ideas.... Let me think.

**Comment by harshmathur1990** [comment]
Hi,

Thank you.  Let me know.

I will check the Path variable this way, However, I did ensure that the System "PATH" variable (set in My computer-> Advanced system settings...) does not have anything related to anaconda or python.

Yes, there is a 64-bit Micromanager installed but in a separate directory (Program Files), I did not remove it because as you said the error points to the correct file path. But I will check this also first thing tomorrow morning (In India).

Thank you again.

Regards,
Harsh

**Comment by harshmathur1990** [comment]
Hi

```
C:\Program Files (x86)\Micro-Manager-2.0>file mmgr_dal_DemoCamera.dll
mmgr_dal_DemoCamera.dll: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
```

I removed all installations of Miromanager and fresh installed 32 bit version, but same error.

**Comment by harshmathur1990** [comment]
Hi,

I figured it out.

Steps:

1.  I checked DLL dependencies for mmgr_dal_DemoCamera.dll (https://stackoverflow.com/questions/7378959/how-to-check-for-dll-dependency)

```
dumpbin /dependents mmgr_dal_DemoCamera.dll
```

```
C:\Program Files (x86)\Micro-Manager-2.0>dumpbin /dependents mmgr_dal_DemoCamera.dll
Microsoft (R) COFF/PE Dumper Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file mmgr_dal_DemoCamera.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    MSVCP100.dll
    MSVCR100.dll

  Summary

        2000 .data
        A000 .rdata
        6000 .reloc
        1000 .rsrc
       25000 .text
```

2. Then I checked for the "file" command on the DLLs mentioned in the output.
3. Turned out "MSVCR100.dll" was of type x86_64.
4. I uninstalled MSVC2010 C++ redistrubutable from program files and manually removed the two files from system32 and syswow64.
5. Reinstalled MSVC 2010 C++ redistributable and everythign worked as expected.

Thank you.

**Comment by marktsuchida** [comment]
@harshmathur1990 Thanks for the update. This is strange, because normally you can safely have both the x86 and x64 versions of the redistributable installed at the same time, and all should work. (The 32-bit version goes in `SysWoW64` and the 64-bit version in `System32`. It's confusing.) I guess somehow your redistributable installation was corrupted; glad it's fixed now.
